---
abstract: 'L<Net::Async::Redis> backend for L<Job::Async>'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Job::Async::Test::Compliance: '0'
  Log::Any::Adapter::TAP: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '0'
  Test::Fatal: '0'
  Test::HexString: '0'
  Test::More: '0.98'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Job-Async-Redis
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Job::Async::Client::Redis:
    file: lib/Job/Async/Client/Redis.pm
    version: '0.004'
  Job::Async::Redis:
    file: lib/Job/Async/Redis.pm
    version: '0.004'
  Job::Async::Worker::Redis:
    file: lib/Job/Async/Worker/Redis.pm
    version: '0.004'
requires:
  Future: '0.37'
  Future::AsyncAwait: '0'
  Future::Utils: '0'
  Getopt::Long: '0'
  IO::Async::Loop: '0'
  IO::Async::Timer::Periodic: '0'
  JSON::MaybeUTF8: '0'
  Job::Async: '0.004'
  Job::Async::Client: '0'
  Job::Async::Utils: '0'
  Job::Async::Worker: '0'
  Log::Any: '1.050'
  Log::Any::Adapter: '0'
  Net::Async::Redis: '2.000'
  Net::Async::Statsd::Client: '0'
  Pod::Usage: '0'
  Ryu::Async: '0'
  Syntax::Keyword::Try: '0'
  curry: '0'
  curry::weak: '0'
  indirect: '0'
  mro: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
version: '0.004'
x_authority: cpan:TEAM
x_contributors:
  - 'Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>'
  - 'Raunak Kathuria <raunakkathuria@gmail.com>'
  - 'tm604 <tom@perlsite.co.uk>'
  - 'mat-fs <53427463+mat-fs@users.noreply.github.com>'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
